### ISSUE TITLE
Adding OOD evaluation to the list of eval methods

### ISSUE THREAD

**Issue by AziziShekoofeh** [funnyzhou/A4SM#1]
Hi,

Thanks for curating this list. As the lead author of ``Robust and Efficient Medical Imaging with Self-Supervision'' I suggest adding evaluation on OOD data to the list of evaluation methods. Behavior of the method on out-of-distribution data is a challenging and unmet need in medical AI and had been overlooked in most of the Medical Self-supervision works, however for the first time in self-supervision setup this aspect has been extensively studied in our new preprint on 15 public and private dataset. Thanks.

**Comment by funnyzhou** [comment]
Hi Shekoofeh,

Sorry for my late reply. 

It is an impressive and practical idea to add evaluation on OOD data to the list of evaluation methods. I'll treat it as a major challenge for SSL in Medical Imaging. By the way, it seems that we lack a thorough summary (paper) about recent work that apply SSL to medical images.

Best,
